version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
    user: root
    ports:
      - "8080:8080"  # Jenkins UI port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  app:
    build:
      context: ./app
    ports:
      - "4000:4000"  # App port for backend
      - "3000:3000"  # App port for frontend
    networks:
      - app-network
    depends_on:
      - prometheus
      - jenkins

  prometheus:
    image: prom/prometheus:latest
    #build:
      
      #context: ./prometheus
    ports:
      - "9090:9090"  # Prometheus UI port
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_home:

